server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
    location /api/ {
        # Point to your Cloud Run URL
        proxy_pass https://parking-backend-740931561798.asia-east1.run.app/;
        
        # Cloud Run requires SNI and the exact Host header
        proxy_ssl_server_name on;
        proxy_set_header Host parking-backend-740931561798.asia-east1.run.app;
        
        # Forward original client IP information
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
